run:
  linters:
    enable:
      - deadcode
      - errcheck
      - gosimple
      - govet
      - ineffassign
      - staticcheck
      - structcheck
      - typecheck
      - unused
      - varcheck
      - asciicheck
      - bodyclose
      - depguard
      - dogsled
      - dupl
      - gochecknoinits
      - gocognit
      - goconst
      - gocritic
      - gocyclo
      - godot
      - gofmt
      - goimports
      - golint
      - gomnd
      - gomodguard
      - goprintffuncname
      - gosec
      - interfacer
      - lll
      - maligned
      - misspell
      - nakedret
      - nestif
      - prealloc
      - rowserrcheck
      - stylecheck
      - testpackage
      - unconvert
      - unparam
      - whitespace
      - wsl
      - scopelint
      - funlen
      - gochecknoglobals
    fast: false